### ISSUE TITLE
Sugestão de melhoria no registro de componentes

### ISSUE THREAD

**Issue by mrdibre** [vitta-health/Vi-Ui#61]
## Description

Foi criado um um arquivo de exportação de todos os componentes do framework,
esse arquivo está localizado em src/componentes/index.js, o motivo pelo qual esse
arquivo foi criado é para ter uma centralização de todos os componentes que estão
sendo utilizado nos framework. Esse arquivo também ajudará no processo de instalação
dos componentes.

Foi modificado o arquivo que registra os componentes do Framework. Assim conseguindo
maior agilidade no registro de componentes já que basta exporta-lo no arquivo citado
acima. Com esse processo também facilitou a configuração do Frawework durante a
instalação.

## Todos

_Fill out or remove list items as needed_

- [x] Criar arquivo de exportação de todos os componentes
- [x] Criar registro automático dos componentes
- [x] Facilitando a configuração do Framework

```javascript
src/components/index.js

// Exportando todos os componentes que estarão disponíveis no framework
export * from './Alert'
export * from './Badge'
export * from './Button'
export * from './ButtonGroup'
export * from './Card'
export * from './Icon'
export * from './Input'
export * from './InputDatepicker'
export * from './InputFile'
export * from './InputRadioCheckbox'
export * from './InputSelect'
export * from './Loading'
export * from './Modal'
export * from './Pagination'
export * from './Table'
export * from './Tabs'
export * from './ToggleSwitch'
export * from './Tooltip'
export * from './Wrapper'

```

```javascript
src/index.js

import * as components from './components'

const ViUi = {
  /**
   * Método responsável por registrar o framework no Vue
   * @param Vue -> instância do Vue em qual o framework será instalado
   * @param Options -> Configurações que poderão ser utilizadas na instalação do framework.
   *  Ex.: A La-carte components e configurações de tema via JS.
   */
  install(Vue, Options) {

    // Instalando os componentes do Framework na instância Vue
    Object.keys(components).forEach(component => {
      let componentName = components[component].name
      // Registrando o componente. Aqui seria interessante fazer a utilização do "A La-Carte componente", o componente
      // só sera registrado caso esteja na lista de componentes informado em Options.
      Vue.component(componentName, components[component])
    })

    // Abaixo fica livre para instalar Vue.directive, Vue.filter e etc.

  },
};

if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(ViUi);
}

export default ViUi;

```
